<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinPager</RootNamespace>
    <AssemblyName>WinPager</AssemblyName>
    <Version>1.0.4</Version>
    <Product>WinPager</Product>
    <Company>WinPager</Company>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

</Project>
